name = "Muffed Mining"
author = "CorneliusCorn"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5197dcbeb9b1815f40ec5bbb7fd3ca510b6dd4b25a690812934796a90392aec4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "datapacks"
