name = "Muffed Mining"
author = "CorneliusCorn"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0cc8bdbdc93918730202cc80533f945962b3956ec46db723610a0ee2324b306"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "datapacks"
