name = "Muffed Mining"
author = "CorneliusCorn"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f82830423dd8534421c484ad68e5114b19e468eda6913038411000d907cf6104"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
