version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
offroad = true
createfood = true
farmersdelight = true
upgrade_aquatic = true
tfmg = true
createplenty = true
deeperdarker = true
createpropulsion = true
oceansdelight = true
strawbed = true
create = true
structurize = true
aeronautics = true
yungscavebiomes = true
numismatics = true
simulated = true
minecolonies = true
stellaris = true
alexscaves = true
create_gravlax = true
bakeries = true
lootr = true
multipiston = true
animal_feeding_trough = true
minecraft = true
boatpropellerbearing = true
create_dragons_plus = true
shippy_ships = true
domum_ornamentum = true
citadel = true
sliceanddice = true
waystones = true
ftboceanmobs = true
ftbquests = true
computercraft = true
moonlight = true
biomesoplenty = true
swplanets = true
sophisticatedbackpacks = true
